### ISSUE TITLE
an error occurred when depth map estimation

### ISSUE THREAD

**Issue by HusBunia** [HGGM-LIM/ABLE#2]
Hi: 
When I run the launch_morph_processing command, there is always an error for the geodesic_mesh 

"MATLAB: geodesic_mesh.h:326: void geodesic::Mesh::build_adjacencies(): ASSERTION 'angle>1e-5 ' failed. killed"

How about this error? and how to solve it? 

Thanks !

**Comment by HusBunia** [comment]
hi Alberto： 
Thanks for your reply ! I have followed your instruction to install SWiM, but I found the traveldepth always be dected as an invalid mexa file in matlab2021. 
It returned error "Invalid MEX-file '/home/opt/able_tool/SWiM-main/mex/travelDepth.mexa64':
/home/opt/able_tool/SWiM-main/mex/travelDepth.mexa64: undefined symbol:
_ZN12MeshAnalyser28ComputeTravelDepthFromClosedEb" 

I guess the mexa could not be correcty linked to the libTraveldepth.a...

The commad I useed to compiled the SWiM like this 
`cmake3 .. -DMINDBOGGLE_INCLUDE_DIR=/home/opt/able_tool/mindboogle/mindboggle-master/vtk_cpp_tools -DMINDBOGGLE_LIBRARY=/home/opt/able_tool/mindboogle/mindboggle-master/vtk_cpp_tools/build/libTravelDepth.a -DVTK_DIR=/home/opt/vtk82/VTK-8.2.0/build
make`  
it gaves me no error and successfully compiled. 

could you gave me some advice? I'm not very familar with mexa file and C compilation, and  I have struggle for this for several days. Looking forward for your help! Thanks.

HusBunia

**Comment by albertofpena** [comment]
Hi, HusBunia:

I'm not sure what the issue might be. I guess you have checked the libMeshAnalyser.a was correctly generated.

Have you tried something like this:

`cmake3 ../ -DMINDBOGGLE_INCLUDE_DIR=/home/opt/able_tool/mindboogle/mindboggle-master/vtk_cpp_tools/build/ -DMINDBOGGLE_LIBRARY=/home/opt/able_tool/mindboogle/mindboggle-master/vtk_cpp_tools/build/libMeshAnalyser.a -DVTK_DIR=/home/opt/vtk82/VTK-8.2.0/build`

removing the fPIC part?

That command is quite similar to the one I use, so I suppose the solution should be close to that.

Let me know if you can make it work or not, so we can find another alternative.

Alberto.

**Comment by HusBunia** [comment]
Hi Alberto,

Thank you for your help!  I finally used the TraveldepthMain file from Mindboggle to generate traveldepth.vtk, which allowed ABLE to process the depth file without shutdown.

I do have another question. I attempted to use MeshFixer to eliminate topological errors in my surface file and I also input the files from fsaverage to ABLE. Unfortunately, both methods gave me a similar error. Do you have any suggestions on specific preprocessing steps I could take before using the tool?

Thank you again for your assistance.

HusBunia

**Comment by albertofpena** [comment]
Hi HusBunia,

I'm sorry I couldn't answer before. Using a program such as MeshFixer or remove_degenerate_faces from gptoolbox could make the surfaces fit for the depth estimation method. However, those processes would likely remove faces and change the connectivity between nodes differently in the pial and white files. The algorithm, as is presented, relies on both surfaces, which should have the same number of vertices and the same node connections for each vertex, so it is expected that, after preprocessing with these tools, ABLE would fail.

What FreeSurfer version are you using? If you want, you could share the pial, white, annot, and curv files for one hemisphere to see if I can find another solution.

Best wishes,
Alberto
